language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_script:
  - git clone https://github.com/glfw/glfw && cd glfw && cmake . && make -j4 && sudo make install && cd ..


script:
  - cmake . && make
